Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # ---------- CATEGORY ----------
    path('category-list', views.category_list, name='category_list'),
    path('category-create', views.category_create, name='category_create'),
    path('category-update/<str:code>/', views.category_update, name='category_update'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    # ---------- PRODUCT ----------
    path('product-list', views.product_list, name='product_list'),
    path('product-create', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-update/<str:code>/', views.product_update, name='product_update'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    # ---------- ENTER PRODUCT ----------
    path('create-enter-product/', views.create_enter_product, name='create_enter_product'),
    path('list-enter-product/', views.list_enter_product, name='list_enter_product'),
    path('detail-enter-product/<str:code>/', views.detail_enter_product, name='detail_enter_product'),
    path('update-enter-product/<str:code>/', views.update_enter_product, name='update_enter_product'),
    path('delete-enter-product/<str:code>/', views.delete_enter_product, name='delete_enter_product'),
    # ---------- PRODUCT IMG ----------
    path('product-img-delete/<int:id>/', views.product_img_delete,name='product_img_delete'),
    path('product-video-delete/<int:id>/', views.product_video_delete,name='product_video_delete'),
    # ---------- PRODUCT HISTORY ----------
    path('product-history/<str:code>/', views.product_history, name='product_history'),
]

main/dashboard/views.py
from django.shortcuts import render, redirect
from main import models
from main.funcs import staff_required
from itertools import chain
from django.db.models import Q
from datetime import datetime

@staff_required 
def index(request):
    context = {}
    return render(request, 'dashboard/index.html', context)

# ---------- CATEGORY ----------

@staff_required 
def category_list(request):
    queryset = models.Category.objects.all()
    context = {
        'queryset':queryset
        }
    return render(request, 'dashboard/category/list.html', context)

@staff_required 
def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')

@staff_required 
def category_update(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.name = request.POST['name']
    queryset.save()
    return redirect('dashboard:category_list')

@staff_required 
def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------- PRODUCT ----------

@staff_required 
def product_list(request):
    categories = models.Category.objects.all()
    category_code = request.GET.get('category_code')
    queryset = models.Product.objects.all()
    filter_items = {}
    for key, value in request.GET.items():
        if key == 'category_code' and value == '0':
            continue
        if value:
            if key == 'start_date':
                key = 'date__gte'
            elif key == 'end_date':
                key = 'date__lte'
            elif key == 'category_code':
                key = 'category__code'
            elif key == 'name':
                key = 'name__icontains'
            elif key == 'price':
                key = 'price__lte'
            elif key == 'is_discount':
                key = 'discount_price__isnull'
                filter_items[key] = False
                continue
            filter_items[key] = value
    queryset = models.Product.objects.filter(**filter_items)
    context = {
          'queryset':queryset,
          'categories':categories,
          'category_code':category_code,
    }
    return render(request, 'dashboard/product/list.html', context)

@staff_required 
def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImg.objects.filter(product=queryset)
    reviews = models.Review.objects.filter(product=queryset)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
          'queryset':queryset,
          'images':images,
          'reviews':reviews,
          'videos':videos
    }
    return render(request, 'dashboard/product/detail.html', context)
    
@staff_required 
def product_create(request):
    categorys = models.Category.objects.all()
    context = {'categorys':categorys}
    if request.method == 'POST':
        delivery = True if request.POST.get('delivery') else False
        product = models.Product.objects.create(
            category_id = request.POST.get('category_id'),
            name = request.POST.get('name'),
            body = request.POST.get('body'),
            price = request.POST.get('price'),
            banner_img = request.FILES.get('banner_img'),
            quantity = request.POST.get('quantity'),
            delivery = delivery
        )
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', context)

@staff_required 
def product_update(request, code):
    images = models.ProductImg.objects.filter(product__code=code)
    videos = models.ProductVideo.objects.filter(product__code=code)
    categories = models.Category.objects.all()
    product = models.Product.objects.get(code=code)

    if request.method == 'POST':
        if request.FILES.get('banner_img'):
            product.banner_img = request.FILES.get('banner_img')
        delivery = True if request.POST.get('delivery') else False
        product.category_code = request.POST.get('category_code')
        product.name = request.POST.get('name')
        product.body = request.POST.get('body')
        product.price = request.POST.get('price') 
        product.delivery = delivery
        product.save()
    
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_update',product.code)
    
    context = {
          'images':images,
          'videos':videos,
          'categories':categories,
          'product':product
    }
    return render(request,'dashboard/product/update.html',context=context)

@staff_required 
def product_delete(request, code):
    product = models.Product.objects.get(code=code)
    product.delete()
    return redirect('dashboard:product_list')

@staff_required 
def product_img_delete(request, id):
    product_img = models.ProductImg.objects.get(id=id)
    product_img.delete()
    return redirect('dashboard:product_list')

@staff_required 
def product_video_delete(request, id):
    product_video = models.ProductVideo.objects.get(id=id)
    product_video.delete()
    return redirect('dashboard:product_update',product_video.product_id)

# ---------- ENTER PRODUCT ----------

@staff_required 
def create_enter_product(request):
    products = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST['code'])
        quantity = request.POST['quantity']
        models.EnterProduct.objects.create(
            product=product,
            quantity=int(quantity),
        )
        return redirect('dashboard:list_enter_product')
    context = {
        'products':products
    }
    return render(request, 'dashboard/enter_product/create.html', context)

@staff_required 
def list_enter_product(request):
    queryset = models.EnterProduct.objects.all()
    context = {
        'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/list.html', context)

@staff_required 
def detail_enter_product(request, code):
    queryset = models.EnterProduct.objects.filter(product__code=code)
    context = {
        'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/detail.html', context)

@staff_required 
def update_enter_product(request, code):
    enter_product = models.EnterProduct.objects.get(code=code)
    products = models.Product.objects.all()
    context = {
        'enter_product':enter_product,
        'products':products
    }
    if request.method == 'POST':
        enter_product.quantity = request.POST.get('quantity') 
        enter_product.date = request.POST.get('date') 
        enter_product.save()
    return render(request, 'dashboard/enter_product/update.html', context)
    
@staff_required 
def delete_enter_product(request, code):
    enter_product = models.EnterProduct.objects.get(code=code)
    enter_product.delete()
    return redirect('dashboard:list_enter_product')    

# ---------- PRODUCT HISTORY ----------

@staff_required 
def product_history(request, code):
    enters = models.EnterProduct.objects.filter(product__code=code)
    outs = models.CartProduct.objects.filter(product__code=code, cart__status=4)
    queryset = list(chain(enters, outs))
    queryset.sort(key=lambda x:x.date, reverse=True)
    result_queryset = []
    for query in queryset:
        try:
            models.EnterProduct.objects.get(code=query.code)
            query.is_enter = True
        except:
            query.is_enter = False
        result_queryset.append(query)
    
    
    return True

templates/dashboard/enter_product/create.html
{% extends 'dashboard/base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Magazin</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                    <a class="breadcrumb-item" href="#">Mahsulot kirimlari</a>
                    <span class="breadcrumb-item active">Yaratish</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Mahsulot yaratish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Mahsulot</label>
                            <div class="col-sm-10">
                                <select name="code" class="form-control">
                                    {% for p in products %}
                                    <option  value="{{p.code}}">{{p.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Soni</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" id="inputPassword3" placeholder="..." name="quantity">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Yaratish</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->


{% endblock %}

templates/dashboard/enter_product/detail.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Magazin</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Mahsulot kirimlari</a>
                <span class="breadcrumb-item active">Batafsil</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-around">
            <h4>Kirimlar ro'yxati</h4>
            
            </div>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Mahsulot</th>
                                <th scope="col">Soni</th>
                                <th scope="col">Vaqti</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for q in queryset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{q.product.name}}</td>
                                <td>{{q.quantity}}</td>
                                <td>{{q.date}}</td>
                                <td>
                                    <a href="{% url 'dashboard:detail_enter_product' q.product.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-eye"></i>
                                    </a>
                                    <a href="{% url 'dashboard:update_enter_product' q.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-edit"></i>
                                    </a>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-delete"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.product.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{q.product.name}}ning kirimini o`chirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:delete_enter_product' q.code %}">
                                                        {% csrf_token %}
                                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/dashboard/enter_product/list.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Magazin</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Mahsulot kirimlari</a>
                <span class="breadcrumb-item active">Ro'yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-around">
            <h4>Kirimlar ro'yxati</h4>
            
            </div>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Mahsulot</th>
                                <th scope="col">Soni</th>
                                <th scope="col">Vaqti</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for q in queryset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{q.product.name}}</td>
                                <td>{{q.quantity}}</td>
                                <td>{{q.date}}</td>
                                <td>
                                    <a href="{% url 'dashboard:detail_enter_product' q.product.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-eye"></i>
                                    </a>
                                    <a href="{% url 'dashboard:update_enter_product' q.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-edit"></i>
                                    </a>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-delete"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.product.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{q.product.name}}ning kirimini o`chirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:delete_enter_product' q.code %}">
                                                        {% csrf_token %}
                                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/dashboard/enter_product/update.html
{% extends 'dashboard/base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Magazin</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                    <a class="breadcrumb-item" href="#">Mahsulot kirimlari</a>
                    <span class="breadcrumb-item active">O'zgartirish</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Mahsulot kirimini o'zgartirish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Mahsulot</label>
                            <div class="col-sm-10">
                                {{enter_product.product.name}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label control-label">Soni</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" name="quantity" value="{{enter_product.quantity}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Vaqti</label>
                            <div class="input-affix m-b-10">
                                <i class="prefix-icon anticon anticon-calendar"></i>
                                <input name="date" type="text" class="form-control datepicker-input" value="{{enter_product.date}}">
                            </div>
                        </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->


{% endblock %}