Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/front/urls.py
from django.urls import path
from . import views


app_name = 'front'


urlpatterns = [
    path('', views.index, name='index'),
    # ---------- CATEGORY ----------
    path('category/<int:id>/', views.category_detail, name='category_detail'),
    # ---------- PRODUCT ----------
    path('product/<str:code>/', views.product_detail, name='product_detail'),
    path('product-list/', views.product_list, name='product_list'),
    path('random-product/', views.random_product, name='random_product'),
    # ---------- CART ----------
    path('carts/', views.carts, name='carts'),
    path('cart/<str:code>/', views.cart_detail, name='cart_detail'),
    path('cart/', views.cart_deactivate, name='cart_deactivate'),
    path('active/cart/', views.active_cart, name='active_cart'),
    path('add-to-cart/<str:code>', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove_from_cart'),
    path('plus-minus/<int:id>/', views.plus_minus, name='plus_minus'),
    # ---------- WISHLIST ----------
    path('list-wishlist/', views.list_wishlist, name='list_wishlist'),
    path('add-to-wishlist/<str:code>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<str:code>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    # ---------- ORDER ----------
    path('list-orders/', views.list_orders, name='list_orders'),
    path('receive-order/<str:code>/', views.receive_order, name='receive_order'),
    path('reject-order/<str:code>/', views.reject_order, name='reject_order'),
]

main/front/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from main import models
from main import funcs
import random




def index(request):
    try:
        products = funcs.wishlist_2(request)
        new_products = funcs.wishlist_2(request, '-date')
    except:
        products = models.Product.objects.all()
        new_products = models.Product.objects.all()
    categories = models.Category.objects.all()
    reviews = models.Review.objects.all().order_by('-mark')
    context = {
        'categories':categories,
        'products':products[:8],
        'new_products':new_products[:4],
        'reviews':reviews[:3]
        }
    return render(request, 'front/index.html',context)

# ---------- CATEGORY ----------

def category_detail(request, id):
    queryset = funcs.wishlist_2(request, category_id=id)
    categories = models.Category.objects.all()
    if request.method == 'GET':
        filtered_items = {}
        my_bool = False
        for key, value in request.GET.items():
            if value:
                if key == 'name':
                    key = 'name__icontains'
                elif key == 'price':
                    start = value.split(';')[0]
                    end = value.split(';')[1]
                    filtered_items['price__gte'] = start
                    filtered_items['price__lte'] = end
                    continue
                elif key == 'filter':
                    if value == '0':
                        continue
                    else:
                        my_bool = True
                        continue
                filtered_items[key] = value
        if my_bool:
            if request.GET.get('filter') == '1':
                queryset = funcs.wishlist_2(request, '-date', category_id=id, **filtered_items)
            elif request.GET.get('filter') == '2':
                queryset = funcs.wishlist_2(request, 'date', category_id=id, **filtered_items)
            elif request.GET.get('filter') == '3':
                queryset = funcs.wishlist_2(request, '-price', category_id=id, **filtered_items)
            elif request.GET.get('filter') == '4':
                queryset = funcs.wishlist_2(request, 'price', category_id=id, **filtered_items)
        else:
                queryset = funcs.wishlist_2(request, category_id=id, **filtered_items)            
    context = {
        'queryset':queryset,
        'categories':categories,
        }
    return render(request, 'front/category/detail.html',context)

# ---------- PRODUCT ----------

def product_detail(request, code):
    product = models.Product.objects.get(code=code)
    reviews = models.Review.objects.filter(product=product)
    images = models.ProductImg.objects.filter(product=product)
    mark = 0
    try:
        for i in reviews:
            mark += i.mark

        mark = int(mark/len(reviews)) if reviews else 0
    except:
        mark = 0
    if request.method =='POST':
        try:
            models.Review.objects.create(
                mark = int(request.POST.get('mark')),
                product = product,
                user = request.user,
                text = request.POST.get('text'),
            )
        except:
            raise ValueError('Xatolik!')
    context = {
        'product':product,
        'mark':mark,
        'rating':range(1,6),
        'images':images,
        'reviews':reviews,
        'result':funcs.wishlist_1(request, code),
    }
    return render(request, 'front/product/detail.html',context)

def product_list(request):
    queryset = funcs.wishlist_2(request)
    categories = models.Category.objects.all()
    if request.method == 'GET':
        filtered_items = {}
        my_bool = False
        for key, value in request.GET.items():
            if value:
                if key == 'name':
                    key = 'name__icontains'
                elif key == 'price':
                    start = value.split(';')[0]
                    end = value.split(';')[1]
                    filtered_items['price__gte'] = start
                    filtered_items['price__lte'] = end
                    continue
                elif key == 'filter':
                    if value == '0':
                        continue
                    else:
                        my_bool = True
                        continue
                filtered_items[key] = value
        if my_bool:
            if request.GET.get('filter') == '1':
                queryset = funcs.wishlist_2(request, '-date', **filtered_items)
            elif request.GET.get('filter') == '2':
                queryset = funcs.wishlist_2(request, 'date', **filtered_items)
            elif request.GET.get('filter') == '3':
                queryset = funcs.wishlist_2(request, '-price', **filtered_items)
            elif request.GET.get('filter') == '4':
                queryset = funcs.wishlist_2(request, 'price', **filtered_items)
        else:
                queryset = funcs.wishlist_2(request, **filtered_items)            
    context = {
        'queryset':queryset,
        'categories':categories,
        }
    return render(request, 'front/product/list.html', context)

def random_product(request):
    product = random.choice(models.Product.objects.all())
    return redirect('front:product_detail', product.code)

# ---------- CART ----------

@login_required(login_url='auth:login')
def carts(request):
    queryset = models.Cart.objects.filter(user=request.user, status=4)
    context = {'queryset':queryset}
    return render(request, 'front/carts/list.html', context)

@login_required(login_url='auth:login')
def active_cart(request):
    queryset , _ = models.Cart.objects.get_or_create(user=request.user, status=1)
    return redirect('front:cart_detail', queryset.code)

@login_required(login_url='auth:login')
def cart_detail(request, code):
    cart = models.Cart.objects.get(code=code)
    queryset = models.CartProduct.objects.filter(cart=cart)
    context = {
        'cart': cart,
        'queryset':queryset,
        }
        
    return render(request, 'front/carts/detail.html', context)

@login_required(login_url='auth:login')
def cart_deactivate(request):
    cart = models.Cart.objects.get(user=request.user, status=1)
    cart_products = models.CartProduct.objects.filter(cart=cart)
    print(cart_products)
    try:
        for product in cart_products:
            p = models.Product.objects.get(code=product.product.code)
            if p.quantity - product.count < 0:
                raise ValueError(f"{p.name} yetarli emas")
            else:
                p.quantity -= product.count
                p.save()
    except:
        raise ValueError("Qaysidir mahsulot yetarli emas")
    cart.status = 2
    cart.save()
    return redirect('front:index')

@login_required(login_url='auth:login')
def add_to_cart(request, code):
    cart = models.Cart.objects.filter(status=1, user=request.user)[0]
    product = models.Product.objects.filter(code=code)[0]
    try:
        cart_product = models.CartProduct.objects.filter(cart=cart, product=product)[0]
        cart_product.count += 1 
        cart_product.save()
    except:
        models.CartProduct.objects.create(
            product = product,
            cart = cart,
            count = 1
        )
    return redirect('front:index')

@login_required(login_url='auth:login')
def remove_from_cart(request, id):
    cart = models.Cart.objects.filter(status=1)[0]
    cart_product = models.CartProduct.objects.filter(id=id)[0]
    cart_product.delete()
    return redirect('front:cart_detail', cart.code)

@login_required(login_url='auth:login')
def plus_minus(request, id):
    product = models.CartProduct.objects.get(id=id)
    code = product.cart.code
    product.count = int(request.POST['count'])
    product.save()
    return redirect('front:cart_detail', code)

# ---------- WISHLIST ----------

@login_required(login_url='auth:login')
def list_wishlist(request):
    queryset = models.WishList.objects.filter(user=request.user)
    context = {
        "queryset":queryset
    }
    return render(request, 'front/wishlist/list.html', context)

@login_required(login_url='auth:login')
def add_to_wishlist(request, code):
    models.WishList.objects.create(
        user = request.user,
        product = models.Product.objects.filter(code=code)[0],
    )
    return redirect('front:list_wishlist')

@login_required(login_url='auth:login')
def remove_from_wishlist(request, code):
    try:
        product = models.WishList.objects.filter(user=request.user, product__code=code)[0]
        product.delete()
    except:
        return redirect('front:index')
    return redirect('front:list_wishlist') 

# ---------- ORDER ----------

@login_required(login_url='auth:login')
def list_orders(request):
    orders = models.Cart.objects.filter(user=request.user, status__in=[2,3])
    context = {
        'orders':orders
    }
    return render(request, 'front/orders/list.html', context)

@login_required(login_url='auth:login')
def receive_order(request, code):
    cart = models.Cart.objects.get(code=code)
    cart.status = 4
    cart.save()
    return redirect('front:list_orders')

@login_required(login_url='auth:login')
def reject_order(request, code):
    cart = models.Cart.objects.get(code=code)
    cart.status = 3
    cart.save()
    return redirect('front:list_orders')

templates/front/product/detail.html
{% extends 'front/base.html' %}
{% load static %}

{% block content %}
<!-- Begin Main Content Area  -->
<main class="main-content">
    <div class="breadcrumb-area breadcrumb-height" data-bg-image="{% static 'front/images/breadcrumb/bg/1-1-1919x388.jpg' %}">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-lg-12">
                    <div class="breadcrumb-item">
                        <h2 class="breadcrumb-heading">Mahsulot</h2>
                        <ul>
                            <li>
                                <a href="{% url 'front:index' %}">Asosiy Sahifa</a>
                            </li>
                            <li>{{product.name}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="single-product-area section-space-top-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="single-product-img">
                        <div class="swiper-container single-product-slider">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <a href="{{product.banner_img.url}}" class="single-img gallery-popup">
                                        <img class="img-full" src="{{product.banner_img.url}}" alt="Product Image">
                                    </a>
                                </div>
                                {% for img in images %}
                                <div class="swiper-slide">
                                    <a href="{{img.img.url}}" class="single-img gallery-popup">
                                        <img class="img-full" src="{{img.img.url}}" alt="Product Image">
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="thumbs-arrow-holder">
                            <div class="swiper-container single-product-thumbs">
                                <div class="swiper-wrapper">
                                    <a href="{{product.banner_img.url}}" class="swiper-slide">
                                        <img class="img-full" src="{{product.banner_img.url}}" alt="Product Thumnail">
                                    </a>
                                    {% for img in images %}
                                    <a href="#" class="swiper-slide">
                                        <img class="img-full" src="{{img.img.url}}" alt="Product Thumnail">
                                    </a>                                      
                                    {% endfor %}
                                </div>
                                <!-- Add Arrows -->
                                <div class=" thumbs-button-wrap d-none d-md-block">
                                    <div class="thumbs-button-prev">
                                        <i class="pe-7s-angle-left"></i>
                                    </div>
                                    <div class="thumbs-button-next">
                                        <i class="pe-7s-angle-right"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 pt-5 pt-lg-0">
                    <div class="single-product-content">
                        <h2 class="title">{{product.name}}</h2>
                        <div class="price-box">
                            <span class="new-price">{{product.price}}</span><br>
                            {% if product.discount_price %}
                            <span class="new-price">Chegirma narx: {{product.discount_price}}</span>
                            {% endif %}
                        </div>
                        <div class="rating-box-wrap pb-4">
                            <div class="rating-box">
                                <ul>
                                    {% for i in rating %}
                                    {% if i <= mark %}
                                    <li><i class="fa fa-star"></i></li>                                      
                                    {% else %}
                                    <li><i class="fa fa-star-o"></i></li>                                      
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="review-status">
                                <a href="#">( {{reviews|length}} Review )</a>
                            </div>
                        </div>
                        <p class="short-desc">
                            {{product.body}}
                        </p>            
                        <ul class="quantity-with-btn">
                            <li class="add-to-cart">
                                <a class="btn btn-custom-size lg-size btn-pronia-primary" href="{% url 'front:add_to_cart' product.code %}">Savatga qo'shish</a>
                            </li>
                            <li class="wishlist-btn-wrap">
                                {% if result %}
                                <a class="custom-circle-btn" href="{% url 'front:remove_from_wishlist' product.code %}">
                                    <i class="fa fa-heart" aria-hidden="true"></i>
                                </a>
                                {% else %}
                                <a class="custom-circle-btn" href="{% url 'front:add_to_wishlist' product.code %}">
                                    <i class="pe-7s-like"></i>
                                </a>
                                {% endif %}
                            </li>
                        </ul>
                        <div class="product-category" style="margin-top: 1rem;">
                            <span class="title">Kategoriyasi :</span>
                            <ul>
                                <li>
                                    <a href="#">{{product.category}}</a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <a href="{{product.qrcode_img.url}}" class="swiper-slide">
                                <img class="img-full" src="{{product.qrcode_img.url}}" alt="Product Thumnail">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="product-tab-area section-space-top-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="nav product-tab-nav tab-style-2 pt-0" role="tablist">
                        <li class="nav-item" role="presentation">
                            <a class="active tab-btn" id="description-tab" data-bs-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">
                                Batafsil
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="tab-btn" id="reviews-tab" data-bs-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="false">
                                Sharhlar({{reviews|length}})
                            </a>
                        </li>
                    </ul>
                        <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                            <div class="product-description-body">
                                <p class="short-desc mb-0">{{product.body}}
                                </p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                            <div class="product-review-body">
                                <div class="blog-comment mt-0">
                                    <h4 class="heading">Izohlar ({{reviews|length}})</h4>
                                    {% for review in reviews %}
                                    <div class="blog-comment-item">
                                        <div class="blog-comment-img">
                                            <img src="{{review.user.avatar.url}}" alt="User Image">
                                        </div>
                                        <div class="blog-comment-content">
                                            <div class="user-meta">
                                                <h2 class="user-name">{{review.user.username}}</h2>
                                            </div>
                                            <p class="user-comment">
                                                {{review.text}}
                                            </p>
                                        </div>
                                    </div>                                      
                                    {% endfor %}
                                </div>
                                {% if user.is_authenticated %}
                                <div class="feedback-area">
                                    <h2 class="heading">Izoh qoldirish</h2>
                                    <form class="feedback-form" method="post">
                                        {% csrf_token %}
                                        <p class="user-comment">Baho:</p>
                                        <div class="form-field mt-30">
                                            <select name="mark" class="input-field">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                        <div class="form-field mt-30">
                                            <textarea name="text" placeholder="Izoh" class="textarea-field"></textarea>
                                        </div>
                                        <div class="button-wrap pt-5">
                                            <button type="submit" class="btn btn-custom-size xl-size btn-pronia-primary">Izoh qoldirish</button>
                                        </div>
                                    </form>
                                </div>
                                {% else %}
                                <h4>Izoh qoldirish uchun login qiling</h4>                                  
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</main>
<!-- Main Content Area End Here  -->
{% endblock content %}