Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # ---------- CATEGORY ----------
    path('category-list', views.category_list, name='category_list'),
    path('category-create', views.category_create, name='category_create'),
    path('category-update/<str:code>/', views.category_update, name='category_update'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    # ---------- PRODUCT ----------
    path('product-list', views.product_list, name='product_list'),
    path('product-create', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-update/<str:code>/', views.product_update, name='product_update'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    # ---------- ENTER PRODUCT ----------
    path('create-enter-product/', views.create_enter_product, name='create_enter_product'),
    path('list-enter-product/', views.list_enter_product, name='list_enter_product'),
    path('detail-enter-product/<str:code>/', views.detail_enter_product, name='detail_enter_product'),
    path('update-enter-product/<str:code>/', views.update_enter_product, name='update_enter_product'),
    path('delete-enter-product/<str:code>/', views.delete_enter_product, name='delete_enter_product'),
    # ---------- PRODUCT IMG ----------
    path('product-img-delete/<int:id>/', views.product_img_delete,name='product_img_delete'),
    path('product-video-delete/<int:id>/', views.product_video_delete,name='product_video_delete'),
    # ---------- PRODUCT HISTORY ----------
    path('product-history/<str:code>/', views.product_history, name='product_history'),
]

main/dashboard/views.py
from django.shortcuts import render, redirect
from main import models
from main.funcs import staff_required
from itertools import chain
from django.db.models import Q
from datetime import datetime

@staff_required 
def index(request):
    context = {}
    return render(request, 'dashboard/index.html', context)

# ---------- CATEGORY ----------

@staff_required 
def category_list(request):
    queryset = models.Category.objects.all()
    context = {
        'queryset':queryset
        }
    return render(request, 'dashboard/category/list.html', context)

@staff_required 
def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')

@staff_required 
def category_update(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.name = request.POST['name']
    queryset.save()
    return redirect('dashboard:category_list')

@staff_required 
def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------- PRODUCT ----------

@staff_required 
def product_list(request):
    categories = models.Category.objects.all()
    category_code = request.GET.get('category_code')
    queryset = models.Product.objects.all()
    filter_items = {}
    for key, value in request.GET.items():
        if key == 'category_code' and value == '0':
            continue
        if value:
            if key == 'start_date':
                key = 'date__gte'
            elif key == 'end_date':
                key = 'date__lte'
            elif key == 'category_code':
                key = 'category__code'
            elif key == 'name':
                key = 'name__icontains'
            elif key == 'price':
                key = 'price__lte'
            elif key == 'is_discount':
                key = 'discount_price__isnull'
                filter_items[key] = False
                continue
            filter_items[key] = value
    queryset = models.Product.objects.filter(**filter_items)
    context = {
          'queryset':queryset,
          'categories':categories,
          'category_code':category_code,
    }
    return render(request, 'dashboard/product/list.html', context)

@staff_required 
def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImg.objects.filter(product=queryset)
    reviews = models.Review.objects.filter(product=queryset)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
          'queryset':queryset,
          'images':images,
          'reviews':reviews,
          'videos':videos
    }
    return render(request, 'dashboard/product/detail.html', context)
    
@staff_required 
def product_create(request):
    categorys = models.Category.objects.all()
    context = {'categorys':categorys}
    if request.method == 'POST':
        delivery = True if request.POST.get('delivery') else False
        product = models.Product.objects.create(
            category_id = request.POST.get('category_id'),
            name = request.POST.get('name'),
            body = request.POST.get('body'),
            price = request.POST.get('price'),
            banner_img = request.FILES.get('banner_img'),
            quantity = request.POST.get('quantity'),
            delivery = delivery
        )
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', context)

@staff_required 
def product_update(request, code):
    images = models.ProductImg.objects.filter(product__code=code)
    videos = models.ProductVideo.objects.filter(product__code=code)
    categories = models.Category.objects.all()
    product = models.Product.objects.get(code=code)

    if request.method == 'POST':
        if request.FILES.get('banner_img'):
            product.banner_img = request.FILES.get('banner_img')
        delivery = True if request.POST.get('delivery') else False
        product.category_code = request.POST.get('category_code')
        product.name = request.POST.get('name')
        product.body = request.POST.get('body')
        product.price = request.POST.get('price') 
        product.delivery = delivery
        product.save()
    
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_update',product.code)
    
    context = {
          'images':images,
          'videos':videos,
          'categories':categories,
          'product':product
    }
    return render(request,'dashboard/product/update.html',context=context)

@staff_required 
def product_delete(request, code):
    product = models.Product.objects.get(code=code)
    product.delete()
    return redirect('dashboard:product_list')

@staff_required 
def product_img_delete(request, id):
    product_img = models.ProductImg.objects.get(id=id)
    product_img.delete()
    return redirect('dashboard:product_list')

@staff_required 
def product_video_delete(request, id):
    product_video = models.ProductVideo.objects.get(id=id)
    product_video.delete()
    return redirect('dashboard:product_update',product_video.product_id)

# ---------- ENTER PRODUCT ----------

@staff_required 
def create_enter_product(request):
    products = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST['code'])
        quantity = request.POST['quantity']
        models.EnterProduct.objects.create(
            product=product,
            quantity=int(quantity),
        )
        return redirect('dashboard:list_enter_product')
    context = {
        'products':products
    }
    return render(request, 'dashboard/enter_product/create.html', context)

@staff_required 
def list_enter_product(request):
    queryset = models.EnterProduct.objects.all()
    context = {
        'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/list.html', context)

@staff_required 
def detail_enter_product(request, code):
    queryset = models.EnterProduct.objects.filter(product__code=code)
    context = {
        'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/detail.html', context)

@staff_required 
def update_enter_product(request, code):
    enter_product = models.EnterProduct.objects.get(code=code)
    products = models.Product.objects.all()
    context = {
        'enter_product':enter_product,
        'products':products
    }
    if request.method == 'POST':
        enter_product.quantity = request.POST.get('quantity') 
        enter_product.date = request.POST.get('date') 
        enter_product.save()
    return render(request, 'dashboard/enter_product/update.html', context)
    
@staff_required 
def delete_enter_product(request, code):
    enter_product = models.EnterProduct.objects.get(code=code)
    enter_product.delete()
    return redirect('dashboard:list_enter_product')    

# ---------- PRODUCT HISTORY ----------

@staff_required 
def product_history(request, code):
    enters = models.EnterProduct.objects.filter(product__code=code)
    outs = models.CartProduct.objects.filter(product__code=code, cart__status=4)
    queryset = list(chain(enters, outs))
    queryset.sort(key=lambda x:x.date, reverse=True)
    result_queryset = []
    for query in queryset:
        try:
            models.EnterProduct.objects.get(code=query.code)
            query.is_enter = True
        except:
            query.is_enter = False
        result_queryset.append(query)
    
    
    return True

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin Panel</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'dashboard/images/logo/favicon.png' %}">

    <!-- page css -->
    <link href="{% static 'dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- Core css -->
    <link href="{% static 'dashboard/css/app.min.css' %}" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="index.html">
                        <img src="{% static 'dashboard/images/logo/logo.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'dashboard/images/logo/logo-fold.png' %}" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="index.html">
                        <img src="{% static 'dashboard/images/logo/logo-white.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'dashboard/images/logo/logo-fold-white.png' %}" alt="Logo">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-15">
                                    <img src="{% static 'dashboard/images/avatars/thumb-3.jpg' %}"  alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="{% static 'dashboard/images/avatars/thumb-3.jpg' %}" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p class="m-b-0 text-dark font-weight-semibold"></p>
                                        </div>
                                    </div>
                                </div>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                            <span class="m-l-10">Profilni yangilash</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Chiqish</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>    
            <!-- Header END -->


            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">
                        <li class="nav-item dropdown open">
                            <a class="dropdown-toggle" href="javascript:void(0);">
                                <span class="icon-holder">
                                    <i class="anticon anticon-appstore"></i>
                                </span>
                                <span class="title">Magazin menusi</span>
                                <span class="arrow">
                                    <i class="arrow-icon"></i>
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="fas fa-folder-open"></i>
                                            </span>
                                            <span class="title">Kategoriya</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:category_create' %}">
                                                    <i class="fas fa-plus-circle"></i>
                                                    Yaratish
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:category_list' %}">
                                                    <span class="icon-holder">
                                                        <i class="fas fa-list-ul"></i>
                                                        Ro'yxat
                                                    </span>  
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </li>
                                
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="fas fa-shopping-basket"></i>
                                            </span>
                                            <span class="title">Mahsulot</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:product_create' %}">
                                                    <i class="fas fa-plus-circle"></i>
                                                    Yaratish
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:product_list' %}">
                                                    <i class="fas fa-list-ul"></i>
                                                    Ro'yxat
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </li>
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="fas fa-sign-in-alt"></i>
                                            </span>
                                            <span class="title">Mahsulot kirimlari</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:create_enter_product' %}">
                                                    <i class="fas fa-plus-circle"></i>
                                                    Yaratish
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:list_enter_product' %}">
                                                    <i class="fas fa-list-ul"></i>
                                                    Ro'yxat
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->

            <!-- Page Container START -->
            <div class="page-container">
                
                {% block content %}
                {% endblock %}
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">© 2024</p>
                        <span>
                            <a href="https://t.me/zane361" class="text-gray m-r-15">Shomalik Davlatov</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="{% static 'dashboard/js/vendors.min.js' %}"></script>

    <!-- page js -->
    <script src="{% static 'dashboard/vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'dashboard/js/pages/dashboard-project.js' %}"></script>
    

    <!-- Core JS -->
    <script src="{% static 'dashboard/js/app.min.js' %}"></script>

</body>

</html>

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% block content %}
<!-- Content Wrapper START -->
         <div class="main-content">
            <div class="page-header no-gutters">
                <div class="d-md-flex align-items-md-center justify-content-between">
                    <div class="media m-v-10 align-items-center">
                        <div class="avatar avatar-image avatar-lg">
                            <img src="{% static 'dashboard/images/avatars/thumb-3.jpg' %}" alt="">
                        </div>
                        <div class="media-body m-l-15">
                            <h4 class="m-b-0">Welcome back</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Wrapper END -->
{% endblock %}